# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.dmat_C <- function(x) {
    .Call('_warptk_dmat', PACKAGE = 'warptk', x)
}

.bs_even_C <- function(time, nk) {
    .Call('_warptk_bs_even', PACKAGE = 'warptk', time, nk)
}

.two_step_warp_C <- function(ymat, wtime, P, niter, nburn, a_eps, b_eps, a_a, b_a, a_c, b_c, a_tau, b_tau) {
    .Call('_warptk_two_step_warp', PACKAGE = 'warptk', ymat, wtime, P, niter, nburn, a_eps, b_eps, a_a, b_a, a_c, b_c, a_tau, b_tau)
}

